# Generated by Django 5.0.1 on 2024-01-12 00:58

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('ingredients', models.CharField(max_length=1000)),
                ('experience_level', multiselectfield.db.fields.MultiSelectField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=255)),
                ('meal_type', multiselectfield.db.fields.MultiSelectField(choices=[('breakfast', 'Breakfast'), ('dinner', 'Dinner'), ('snack', 'Snack'), ('desert', 'Desert')], max_length=255)),
                ('equipment_needed', multiselectfield.db.fields.MultiSelectField(choices=[('slowcooker', 'Slow Cooker'), ('instantpot', 'Pressure Cooker'), ('handmixer', 'Hand Mixer'), ('standmixer', 'Stand Mixer'), ('blender', 'Blender'), ('immersionblender', 'Immersion Blender'), ('foodprocessor', 'Food Processor'), ('grill', 'Grill'), ('none', 'None')], max_length=255)),
                ('allergen', multiselectfield.db.fields.MultiSelectField(choices=[('sesame', 'Sesame'), ('gluten', 'Gluten'), ('treenuts', 'Tree Nuts'), ('peanuts', 'Peanuts'), ('soy', 'Soy'), ('wheat', 'Wheat'), ('eggs', 'Eggs'), ('shellfish', 'Shellfish'), ('fish', 'Fish'), ('milk', 'Milk'), ('none', 'None')], max_length=255)),
                ('time_commitment', multiselectfield.db.fields.MultiSelectField(choices=[('under30', 'Under 30 Minutes'), ('under60', 'Under 60 Minutes'), ('over60', 'Over 60 minutes, less than 3 hours'), ('slowcook', 'Slow cooker meal, set it and forget it'), ('multiday', 'Can take multiple days to make')], max_length=255)),
                ('instructions', models.TextField()),
            ],
        ),
    ]
