# Generated by Django 5.0.1 on 2024-01-12 01:59

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0004_alter_recipe_allergen_alter_recipe_equipment_needed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='equipment_needed',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('slowcooker', 'Slow Cooker'), ('instantpot', 'Pressure Cooker'), ('handmixer', 'Hand Mixer'), ('standmixer', 'Stand Mixer'), ('blender', 'Blender'), ('immersionblender', 'Immersion Blender'), ('foodprocessor', 'Food Processor'), ('grill', 'Grill'), ('none-equipment', 'None')], max_length=255),
        ),
    ]
