# Generated by Django 5.0.1 on 2024-01-13 00:57

import recipe_app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0006_remove_recipe_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='allergen',
            field=recipe_app.models.MultiSelectField(choices=[('sesame', 'Sesame'), ('gluten', 'Gluten'), ('treenuts', 'Tree Nuts'), ('peanuts', 'Peanuts'), ('soy', 'Soy'), ('wheat', 'Wheat'), ('eggs', 'Eggs'), ('shellfish', 'Shellfish'), ('fish', 'Fish'), ('milk', 'Milk'), ('none_allergen', 'None')], max_length=255),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='equipment_needed',
            field=recipe_app.models.MultiSelectField(choices=[('slowcooker', 'Slow Cooker'), ('instantpot', 'Pressure Cooker'), ('handmixer', 'Hand Mixer'), ('standmixer', 'Stand Mixer'), ('blender', 'Blender'), ('immersionblender', 'Immersion Blender'), ('foodprocessor', 'Food Processor'), ('grill', 'Grill'), ('none-equipment', 'None')], max_length=255),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='experience_level',
            field=recipe_app.models.MultiSelectField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=255),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='meal_type',
            field=recipe_app.models.MultiSelectField(choices=[('breakfast', 'Breakfast'), ('dinner', 'Dinner'), ('snack', 'Snack'), ('desert', 'Desert')], max_length=255),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='time_commitment',
            field=recipe_app.models.MultiSelectField(choices=[('under30', 'Under 30 Minutes'), ('under60', 'Under 60 Minutes'), ('over60', 'Over 60 minutes, less than 3 hours'), ('slowcook', 'Slow cooker meal, set it and forget it'), ('multiday', 'Can take multiple days to make')], max_length=255),
        ),
    ]
