# Generated by Django 5.0.1 on 2024-01-13 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0007_alter_recipe_allergen_alter_recipe_equipment_needed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='allergen',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='equipment_needed',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='experience_level',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='meal_type',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='time_commitment',
        ),
    ]
