# Generated by Django 5.0.1 on 2024-01-13 01:06

import recipe_app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0008_remove_recipe_allergen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='experience_level',
            field=recipe_app.models.MultiSelectField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=255),
        ),
    ]
