# Generated by Django 4.2.1 on 2024-01-13 01:22

from django.db import migrations, models
import recipe_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0009_recipe_experience_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='allergen',
            field=recipe_app.models.MultiSelectField(choices=[('sesame', 'Sesame'), ('gluten', 'Gluten'), ('treenuts', 'Tree Nuts'), ('peanuts', 'Peanuts'), ('soy', 'Soy'), ('wheat', 'Wheat'), ('eggs', 'Eggs'), ('shellfish', 'Shellfish'), ('fish', 'Fish'), ('milk', 'Milk'), ('none_allergen', 'None')], default='none_allergen', max_length=255),
        ),
        migrations.AddField(
            model_name='recipe',
            name='equipment_needed',
            field=recipe_app.models.MultiSelectField(choices=[('slowcooker', 'Slow Cooker'), ('instantpot', 'Pressure Cooker'), ('handmixer', 'Hand Mixer'), ('standmixer', 'Stand Mixer'), ('blender', 'Blender'), ('immersionblender', 'Immersion Blender'), ('foodprocessor', 'Food Processor'), ('grill', 'Grill'), ('none-equipment', 'None')], default='none-equipment', max_length=255),
        ),
        migrations.AddField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(default='no instructions, sorry'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='meal_type',
            field=recipe_app.models.MultiSelectField(choices=[('breakfast', 'Breakfast'), ('dinner', 'Dinner'), ('snack', 'Snack'), ('desert', 'Desert')], default='breakfast', max_length=255),
        ),
        migrations.AddField(
            model_name='recipe',
            name='time_commitment',
            field=recipe_app.models.MultiSelectField(choices=[('under30', 'Under 30 Minutes'), ('under60', 'Under 60 Minutes'), ('over60', 'Over 60 minutes, less than 3 hours'), ('slowcook', 'Slow cooker meal, set it and forget it'), ('multiday', 'Can take multiple days to make')], default='under30', max_length=255),
        ),
    ]
