# Generated by Django 4.2.1 on 2024-01-18 16:05

from django.db import migrations
import recipe_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0010_recipe_allergen_recipe_equipment_needed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='meal_type',
            field=recipe_app.models.MultiSelectField(choices=[('breakfast', 'Breakfast'), ('dinner', 'Dinner'), ('snack', 'Snack'), ('dessert', 'Dessert')], default='breakfast', max_length=255),
        ),
    ]
